version: "2.4"
services:
    botai:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'echo ready || exit 1'"]
            interval: 10s
            timeout: 10s
            retries: 5